### ISSUE TITLE
Expand WPF Support

### ISSUE THREAD

**Issue by adamhewitt627** [bitstadium/HockeyApp-for-Windows#5]
I mainly want events and user metrics, and am willing to work and PR it, but before I waste my time:
1. Is this even wanted? (Would my PR be accepted?)
2. Are there technical hurdles/reasons it hasn't been done yet, or just time/resources?

**Comment by ElektrojungeAtWork** [comment]
Hey Adam,

thanks so much for getting in touch!
We wanted to do this for quite some time but mostly time/resources kept us from doing it.

Part of me wants to say "go for it" but since HockeyApp will transition to it's next incarnation, which is Mobil Center (the anouncement is [in the HockeyApp Blog](https://www.hockeyapp.net/blog/2016/11/16/mobile-center-next-generation-hockeyapp.html)).

For WinForms/WPF, this means that we have created a community branch that accepts all PRs and we do a sanity check for it but we will focus on Mobile Center. There's a [blogpost](https://www.hockeyapp.net/blog/2017/01/30/hockeysdk-windows-4-1-6.html) about this, too.

I hope that I answered your questions. Let me know if I can be of more help!

Have a great weekend

*wavesTowardsSpokane*

Benny
